# Generated by Django 3.1.2 on 2021-05-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, verbose_name='Номер телефона'),
        ),
    ]
