# Generated by Django 3.1.2 on 2021-05-16 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OrderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='distance',
            field=models.FloatField(default=1000, verbose_name='Расстояние между адресами'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_volume',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Объем груза (куб. метры'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_weight',
            field=models.IntegerField(verbose_name='Вес груза (кг.)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
