# Generated by Django 3.1.2 on 2021-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0002_auto_20210516_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Цена заказа'),
            preserve_default=False,
        ),
    ]
