# Generated by Django 3.1.2 on 2021-05-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderApp', '0004_auto_20210516_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Расстояние между адресами'),
        ),
    ]
